#!/usr/bin/env bash
# ****************************************************
#
#   Setup - ZSH
#
# ****************************************************

cd ~
rm -rf ~/.z*
echo 'cloning zsh prezto fork'
git clone --recursive https://github.com/bradbergeron-us/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

cd ~/.zprezto
git pull && git submodule update --init --recursive
echo 'Updatting submodules'
